local A, L = ...

local rLib = L.rLib

if L.C.styleRollHistory then
    ContainerFrameCombinedBags.NineSlice.TopLeftCorner:SetAlpha(0)
    ContainerFrameCombinedBags.NineSlice.TopEdge:SetAlpha(0)
    ContainerFrameCombinedBags.NineSlice.TopRightCorner:SetAlpha(0)
    ContainerFrameCombinedBags.NineSlice.RightEdge:SetAlpha(0)
    ContainerFrameCombinedBags.NineSlice.BottomRightCorner:SetAlpha(0)
    ContainerFrameCombinedBags.NineSlice.BottomEdge:SetAlpha(0)
    ContainerFrameCombinedBags.NineSlice.BottomLeftCorner:SetAlpha(0)
    ContainerFrameCombinedBags.NineSlice.LeftEdge:SetAlpha(0)
    ContainerFrameCombinedBags.TitleContainer:Hide()
    ContainerFrameCombinedBags.MoneyFrame.Border:SetAlpha(0)
    ContainerFrameCombinedBagsPortrait:Hide()
    ContainerFrameCombinedBagsPortraitButton:Hide()
    ContainerFrameCombinedBags.CloseButton:Hide(0)

    ContainerFrame1.NineSlice.TopLeftCorner:SetAlpha(0)
    ContainerFrame1.NineSlice.TopEdge:SetAlpha(0)
    ContainerFrame1.NineSlice.TopRightCorner:SetAlpha(0)
    ContainerFrame1.NineSlice.RightEdge:SetAlpha(0)
    ContainerFrame1.NineSlice.BottomRightCorner:SetAlpha(0)
    ContainerFrame1.NineSlice.BottomEdge:SetAlpha(0)
    ContainerFrame1.NineSlice.BottomLeftCorner:SetAlpha(0)
    ContainerFrame1.NineSlice.LeftEdge:SetAlpha(0)
    ContainerFrame1.TitleContainer:Hide()
    ContainerFrame1Portrait:Hide()
    ContainerFrame1PortraitButton:Hide()
    ContainerFrame1.CloseButton:Hide(0)

    ContainerFrame2.NineSlice.TopLeftCorner:SetAlpha(0)
    ContainerFrame2.NineSlice.TopEdge:SetAlpha(0)
    ContainerFrame2.NineSlice.TopRightCorner:SetAlpha(0)
    ContainerFrame2.NineSlice.RightEdge:SetAlpha(0)
    ContainerFrame2.NineSlice.BottomRightCorner:SetAlpha(0)
    ContainerFrame2.NineSlice.BottomEdge:SetAlpha(0)
    ContainerFrame2.NineSlice.BottomLeftCorner:SetAlpha(0)
    ContainerFrame2.NineSlice.LeftEdge:SetAlpha(0)
    ContainerFrame2.TitleContainer:Hide()
    ContainerFrame2Portrait:Hide()
    ContainerFrame2PortraitButton:Hide()
    ContainerFrame2.CloseButton:Hide(0)

    ContainerFrame3.NineSlice.TopLeftCorner:SetAlpha(0)
    ContainerFrame3.NineSlice.TopEdge:SetAlpha(0)
    ContainerFrame3.NineSlice.TopRightCorner:SetAlpha(0)
    ContainerFrame3.NineSlice.RightEdge:SetAlpha(0)
    ContainerFrame3.NineSlice.BottomRightCorner:SetAlpha(0)
    ContainerFrame3.NineSlice.BottomEdge:SetAlpha(0)
    ContainerFrame3.NineSlice.BottomLeftCorner:SetAlpha(0)
    ContainerFrame3.NineSlice.LeftEdge:SetAlpha(0)
    ContainerFrame3.TitleContainer:Hide()
    ContainerFrame3Portrait:Hide()
    ContainerFrame3PortraitButton:Hide()
    ContainerFrame3.CloseButton:Hide(0)

    ContainerFrame4.NineSlice.TopLeftCorner:SetAlpha(0)
    ContainerFrame4.NineSlice.TopEdge:SetAlpha(0)
    ContainerFrame4.NineSlice.TopRightCorner:SetAlpha(0)
    ContainerFrame4.NineSlice.RightEdge:SetAlpha(0)
    ContainerFrame4.NineSlice.BottomRightCorner:SetAlpha(0)
    ContainerFrame4.NineSlice.BottomEdge:SetAlpha(0)
    ContainerFrame4.NineSlice.BottomLeftCorner:SetAlpha(0)
    ContainerFrame4.NineSlice.LeftEdge:SetAlpha(0)
    ContainerFrame4.TitleContainer:Hide()
    ContainerFrame4Portrait:Hide()
    ContainerFrame4PortraitButton:Hide()
    ContainerFrame4.CloseButton:Hide(0)

    ContainerFrame5.NineSlice.TopLeftCorner:SetAlpha(0)
    ContainerFrame5.NineSlice.TopEdge:SetAlpha(0)
    ContainerFrame5.NineSlice.TopRightCorner:SetAlpha(0)
    ContainerFrame5.NineSlice.RightEdge:SetAlpha(0)
    ContainerFrame5.NineSlice.BottomRightCorner:SetAlpha(0)
    ContainerFrame5.NineSlice.BottomEdge:SetAlpha(0)
    ContainerFrame5.NineSlice.BottomLeftCorner:SetAlpha(0)
    ContainerFrame5.NineSlice.LeftEdge:SetAlpha(0)
    ContainerFrame5.TitleContainer:Hide()
    ContainerFrame5Portrait:Hide()
    ContainerFrame5PortraitButton:Hide()
    ContainerFrame5.CloseButton:Hide(0)

    ContainerFrame6.NineSlice.TopLeftCorner:SetAlpha(0)
    ContainerFrame6.NineSlice.TopEdge:SetAlpha(0)
    ContainerFrame6.NineSlice.TopRightCorner:SetAlpha(0)
    ContainerFrame6.NineSlice.RightEdge:SetAlpha(0)
    ContainerFrame6.NineSlice.BottomRightCorner:SetAlpha(0)
    ContainerFrame6.NineSlice.BottomEdge:SetAlpha(0)
    ContainerFrame6.NineSlice.BottomLeftCorner:SetAlpha(0)
    ContainerFrame6.NineSlice.LeftEdge:SetAlpha(0)
    ContainerFrame6.TitleContainer:Hide()
    ContainerFrame6Portrait:Hide()
    ContainerFrame6PortraitButton:Hide()
    ContainerFrame6.CloseButton:Hide(0)
end
